travis:
  secure:
    BINSTAR_TOKEN: lESLKlnL4vcSWBKJpirO0fLgWBmSCmXbDvGXyaN23iZuPSdyajrcuW+rOjvJ2QTVFiCQZ1CE5f25hsgTCHE3eNBxYsyWCOxr48K0OEUCsfmgsDFXobPDPFtIM+1ohdr//vrtmOip+ZuRHNWIN5fpsoHzLez1UI/EjqValXxVoZaJV8Qb+O/JLrKh5JcHwcw+8VZ0iRWDTqMsvnklOkmn3YLdbLYsRquQBI2xzcUpKjvgyG88yEmwheXO7xE7gCkn0cpGm15zZtSHTt9wJKCkT7arW3X0+/HQ1C8WDEClWJLrL2CB7VYyooBRUuoWcmn3vwM1kk8KQm0azk9ioCynyYpdwDOY86IdRwyCP8eN1HSaqLH+Y1ZOVzVXVi+6cV42NJWT34ve5tjYUS8AcdXRHoNqkvLjuYX0Tn/ZpfxltElw7bfHLQXf4tcSKZRAYVoINe5WznvNqkiafIbV1p7rhytwJH9KEsb0ta4u5SSYQYomojyPNXqlfvtc7RN2tbdLePo6bnUrik8PgrgV973wcbvY/kxba3jAFUGaa6hnCmVLBeZgkoC8o+cqaWtumvS9YfKzTqXi8DoE3OLmfbFrv/+oNjIU/x4vZpYap7cT7Eq6mlTwuicASjzebplwzBLU5eCpOdJ+ZmvBT5HuOt9XoDg9GW1aOn5mR32haFLRHKo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
